name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # Change to 'main' if your default branch is 'main'

permissions:
  contents: write  # Required to push to the repository
  pages: write     # Required to deploy to GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the Node.js version

    - name: Install dependencies
      run: npm ci  # Use 'ci' for clean install

    - name: Build the Angular app
      run: npm run build -- --base-href="/sdk-finance-invoice/"
      env:
        CI: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/sdk-finance-invoice

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Configure Git
      run: |
        git config --global user.name "bohdankolodiy"
        git config --global user.email "b.kolodiy@binariks.com"

    - name: Deploy to GitHub Pages
      run: ng deploy --base-href="/sdk-finance-invoice/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
